export enum RepositoryError {
  'REPOSITORY_NOT_IMPLEMENT' = 'REPOSITORY_NOT_IMPLEMENT',
  'REPOSITORY_INVALID_PROJECTION' = 'REPOSITORY_INVALID_PROJECTION',
  'REPOSITORY_BAD_REQUEST' = 'REPOSITORY_BAD_REQUEST',
  'REPOSITORY_BAD_RESULT' = 'REPOSITORY_BAD_RESULT',
}
