export enum ActionType {
  ORDER_TYPE_BUY = 'ORDER_TYPE_BUY',
  ORDER_TYPE_SELL = 'ORDER_TYPE_SELL',
  ORDER_TYPE_BUY_LIMIT = 'ORDER_TYPE_BUY_LIMIT',
  ORDER_TYPE_SELL_LIMIT = 'ORDER_TYPE_SELL_LIMIT',
  ORDER_TYPE_BUY_STOP = 'ORDER_TYPE_BUY_STOP',
  ORDER_TYPE_SELL_STOP = 'ORDER_TYPE_SELL_STOP',
  POSITION_TYPE_BUY = 'POSITION_TYPE_BUY',
  POSITION_TYPE_SELL = 'POSITION_TYPE_SELL',
  DEAL_TYPE_BUY = 'DEAL_TYPE_BUY',
  DEAL_TYPE_SELL = 'DEAL_TYPE_SELL',
}

export enum OrderState {
  ORDER_STATE_FILLED = 'ORDER_STATE_FILLED',
}

export enum EntryType {
  DEAL_ENTRY_IN = 'DEAL_ENTRY_IN',
  DEAL_ENTRY_OUT = 'DEAL_ENTRY_OUT',
}
