import Link from '~components/base/Link';
import Group from '~ui/core/Group';
import Image from '~ui/core/Image';
import Stack from '~ui/core/Stack';
import Text from '~ui/core/Text';
import Title from '~ui/core/Title';

function Signals() {
  return (
    <Stack>
      <Title ta="center" size="h2">A Gift For You: Trading Signals</Title>
      <Title ta="center" size="h4">
        We publish trading signals that are actively used for trading purposes,
        generated by our advanced, professional-grade bots.
        These signals are designed to offer timely and accurate market insights
        to make well-informed trading decisions
      </Title>
      <Group position="center">
        <Image
          src="/icons/signals.jpg"
          alt="signals"
          radius="lg"
          fit="contain"
          width="100%"
          sx={{ maxWidth: 600 }}
        />
      </Group>

      <Title ta="center" size="h4">Stay updated on our public trading signals through these channels below</Title>
      <Group position="center" spacing="xl">
        <Link href="https://discord.gg/HAC92XvHdb" target="_blank" variant="noColor">
          <Group spacing="xs">
            <Image
              src="/icons/discord.png"
              alt="discord"
              fit="contain"
              width="100%"
              sx={{ maxWidth: 30 }}
            />
            <Text size="lg">Discord</Text>
          </Group>
        </Link>
        <Link href="https://t.me/fishprovider_signals" target="_blank" variant="noColor">
          <Group spacing="xs">
            <Image
              src="/icons/tele.png"
              alt="telegram"
              fit="contain"
              width="100%"
              sx={{ maxWidth: 30 }}
            />
            <Text size="lg">Telegram</Text>
          </Group>
        </Link>
      </Group>
    </Stack>
  );
}

export default Signals;
